### ISSUE TITLE
Calibrate Data

### ISSUE THREAD

**Issue by Theresa24** [Dih5/mcareader#3]
Hi again,

since I'm always using uncalibrated data, I wanted to ask whether mcareader has an option to perform the calibration afterwards?

Thanks and best regards,
Theresa

**Comment by Dih5** [comment]
Hello again, Theresa,

I think we have deja-vu this [here](https://github.com/Dih5/mcareader/issues/2#issuecomment-336815878). Or do you mean something else?

**Comment by Theresa24** [comment]
Thanks, I completely overlooked it!

**Comment by Dih5** [comment]
Ok, glad it served you :smile:
